AvivaFizzBuzzCode/AvivaFizzBuzzCode/Models/FizzBuzzModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AvivaFizzBuzzCode.Models
{
    public class FizzBuzzModel
    {
        public int MaxLimit { get; set; }

        public List<KeyValuePair<string, string>> FizzBussList { get; set; }

        public string Color { get; set; }
    }
}

AvivaFizzBuzzCode/AvivaFizzBuzzCode/Controllers/FizzBuzzController.cs
using AvivaFizzBuzzCode.Models;
using Moq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvivaFizzBuzzCode.Controllers
{
    public class FizzBuzzController : Controller
    {
        //
        // GET: /FizzBuzz/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MyFizzBuzz()
        {
            return View();
        }
        public ViewResult DisplayResult()
        {
            FizzBuzzModel fizzbuzzmodel = new FizzBuzzModel();

            fizzbuzzmodel.MaxLimit = Convert.ToInt32(Request.Form["MaxLimit"]);
            fizzbuzzmodel.FizzBussList = new List<KeyValuePair<string, string>>();

            WordSelector ws = new WordSelector();

            for (int count = 1; count <= fizzbuzzmodel.MaxLimit; count++)
            {
                string result = string.Empty;
                string Color = string.Empty;
                KeyValuePair<string, string> keyval;
                if (count % 3 == 0)
                {
                    result += ws.GetWordfortheDay("Fizz");
                    Color = "color:#0000CC ;";
                }
                if (count % 5 == 0)
                {
                    result += ws.GetWordfortheDay("Buzz"); ;
                    Color = "color:#009900 ;";
                }
                if (string.IsNullOrEmpty(result))
                {
                    result = count.ToString();
                    Color = "color:#000000 ;";
                }

                keyval = new KeyValuePair<string, string>(result, Color);
                fizzbuzzmodel.FizzBussList.Add(keyval);
            }

            return View(fizzbuzzmodel);
        }

        private void CallWebservicetoLog(string uservalue)
        {
            var mockDataAccess = new Mock<IWebServiceInterfacecs>();
            //mockDataAccess.Setup(m => m.CallWebserviceTolog(uservalue));
        }

    }
}

AvivaFizzBuzzCode/AvivaFizzBuzzCode/Views/FizzBuzz/DisplayResult.cshtml
@model AvivaFizzBuzzCode.Models.FizzBuzzModel


@{
    Layout = null;
  

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DispayResult</title>
</head>
<body>
    <div>
      <ul>
@foreach (var item in Model.FizzBussList)
{
   <li style="@item.Value">@item.Key</li>
}
</ul>  
    </div>
</body>
</html>

AvivaFizzBuzzCode/AvivaFizzBuzzCode/Views/FizzBuzz/MyFizzBuzz.cshtml
@model AvivaFizzBuzzCode.Models.FizzBuzzModel

@{
    Layout = null;
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MyFizzBuzz</title>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
<body>
    <div ng-app>
        <form id="frm1" action="@Url.Action("DisplayResult", "FizzBuzz")"  name="frm1" method="post">
            <input type="number" name="MaxLimit" value="" ng-model="MaxLimit" id="MaxLimit" min="1" max="1000" required />             
            <br/>
            <br/>
            <input ng-disabled="!frm1.$valid" type="submit" name="Print" value="Submit" />
            <br/>
        </form>
    </div>
    
</body>
</html>

AvivaFizzBuzzCode/AvivaFizzBuzzCode/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>